version: '3.8'

services:
  backend:
    build:
      context: ./calculator-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./calculator-frontend
    ports:
      - "80:80"  # Since Nginx in our Dockerfile serves on port 80
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

