version: '3.8'

services:
  backend:
    build:
      context: ./calculator-backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./calculator-frontend
    ports:
      - "3000:3000"  # Since Nginx in our Dockerfile serves on port 3000
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

